[package]
name = "beatcancer"
version = "0.1.0"
edition = "2023_01"

[dependencies]
starknet = ">=2.6.3"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.11.0" }


[[target.starknet-contract]]
sierra = true
casm = true
